import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const users = sqliteTable("users", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  createdAt: integer("created_at").notNull(),
});

export const sessions = sqliteTable("sessions", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  expiresAt: integer("expires_at").notNull(),
});

export const organizations = sqliteTable("organizations", {
  id: text("id").primaryKey(),
  ownerUserId: text("owner_user_id").notNull(),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  creditsUsed: integer("credits_used").notNull().default(0),
  creditsLimit: integer("credits_limit").notNull().default(50),
  projectLimit: integer("project_limit").notNull().default(5),
  latencyMinMs: integer("latency_min_ms").notNull().default(2000),
  latencyMaxMs: integer("latency_max_ms").notNull().default(6000),
  failureRate: integer("failure_rate").notNull().default(15),
  retryDelaysJson: text("retry_delays_json").notNull().default("[10000,30000,60000]"),
  storageBaseUrl: text("storage_base_url"),
  storageStatus: text("storage_status").notNull().default("none"),
  createdAt: integer("created_at").notNull(),
});

export const projects = sqliteTable("projects", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull(),
  name: text("name").notNull(),
  cnpj: text("cnpj").notNull(),
  razaoSocial: text("razao_social").notNull(),
  inscricaoMunicipal: text("inscricao_municipal"),
  inscricaoEstadual: text("inscricao_estadual"),
  regimeTributario: text("regime_tributario").notNull().default("3"),
  codigoMunicipio: text("codigo_municipio"),
  email: text("email"),
  telefone: text("telefone"),
  description: text("description"),
  enderecoJson: text("endereco_json").notNull().default("{}"),
  codigoTributacao: text("codigo_tributacao"),
  tributacaoIss: integer("tributacao_iss").default(1),
  serieNfse: text("serie_nfse").notNull().default("1608"),
  aliquotaSimples: real("aliquota_simples"),
  regimeIss: integer("regime_iss"),
  codigoServicoSp: text("codigo_servico_sp"),
  cnae: text("cnae"),
  basicAuthUsuario: text("basic_auth_usuario"),
  basicAuthSenha: text("basic_auth_senha"),
  ultimoNumeroNfse: integer("ultimo_numero_nfse").notNull().default(0),
  defaultNbs: text("default_nbs"),
  defaultCstIbscbs: text("default_cst_ibscbs"),
  defaultClassificacao: text("default_classificacao"),
  defaultIndicador: text("default_indicador"),
  cstPisCofins: text("cst_pis_cofins"),
  aliquotaPis: real("aliquota_pis"),
  aliquotaCofins: real("aliquota_cofins"),
  active: integer("active").notNull().default(1),
  certFileName: text("cert_file_name"),
  certUploadedAt: integer("cert_uploaded_at"),
  logoDataUrl: text("logo_data_url"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const apiKeys = sqliteTable("api_keys", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull(),
  projectId: text("project_id"),
  kind: text("kind").notNull(),
  name: text("name").notNull(),
  keyHash: text("key_hash").notNull().unique(),
  keyPrefix: text("key_prefix").notNull(),
  scopesJson: text("scopes_json").notNull(),
  rateLimitPerMinute: integer("rate_limit_per_minute").notNull(),
  active: integer("active").notNull().default(1),
  lastUsedAt: integer("last_used_at"),
  createdAt: integer("created_at").notNull(),
});

export const invoices = sqliteTable("invoices", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull(),
  projectId: text("project_id").notNull(),
  status: text("status").notNull(),
  payloadJson: text("payload_json").notNull(),
  tomadorNome: text("tomador_nome").notNull().default(""),
  valorTotal: real("valor_total").notNull().default(0),
  competencia: text("competencia"),
  referencia: text("referencia"),
  timelineJson: text("timeline_json").notNull().default("[]"),
  simResult: text("sim_result").notNull(),
  simDelayMs: integer("sim_delay_ms").notNull(),
  simSource: text("sim_source").notNull(),
  readyAt: integer("ready_at").notNull(),
  processAfter: integer("process_after"),
  numeroNfse: text("numero_nfse"),
  serie: text("serie"),
  chNfse: text("ch_nfse"),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  cancelMotivo: text("cancel_motivo"),
  cancelCodigo: integer("cancel_codigo"),
  cancelResult: text("cancel_result"),
  cancelDelayMs: integer("cancel_delay_ms"),
  cancelSource: text("cancel_source"),
  cancelError: text("cancel_error"),
  issuedAt: integer("issued_at"),
  cancelledAt: integer("cancelled_at"),
  idempotencyKey: text("idempotency_key"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const idempotency = sqliteTable("idempotency", {
  id: text("id").primaryKey(),
  scopeId: text("scope_id").notNull(),
  idemKey: text("idem_key").notNull(),
  method: text("method").notNull(),
  path: text("path").notNull(),
  bodyHash: text("body_hash").notNull(),
  statusCode: integer("status_code").notNull(),
  responseJson: text("response_json").notNull(),
  createdAt: integer("created_at").notNull(),
});

export const webhookEndpoints = sqliteTable("webhook_endpoints", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull(),
  projectId: text("project_id").notNull(),
  url: text("url").notNull(),
  eventsJson: text("events_json").notNull(),
  secret: text("secret"),
  active: integer("active").notNull().default(1),
  createdAt: integer("created_at").notNull(),
});

export const webhookDeliveries = sqliteTable("webhook_deliveries", {
  id: text("id").primaryKey(),
  endpointId: text("endpoint_id").notNull(),
  organizationId: text("organization_id").notNull(),
  projectId: text("project_id").notNull(),
  invoiceId: text("invoice_id"),
  event: text("event").notNull(),
  url: text("url").notNull(),
  payloadJson: text("payload_json").notNull(),
  status: text("status").notNull(),
  attempts: integer("attempts").notNull().default(0),
  nextAttemptAt: integer("next_attempt_at").notNull(),
  lastStatusCode: integer("last_status_code"),
  lastError: text("last_error"),
  createdAt: integer("created_at").notNull(),
});

export const requestLogs = sqliteTable("request_logs", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id"),
  projectId: text("project_id"),
  apiKeyId: text("api_key_id"),
  keyPrefix: text("key_prefix"),
  method: text("method").notNull(),
  path: text("path").notNull(),
  statusCode: integer("status_code").notNull(),
  durationMs: integer("duration_ms").notNull(),
  createdAt: integer("created_at").notNull(),
});

export const emailOutbox = sqliteTable("email_outbox", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id").notNull(),
  invoiceId: text("invoice_id").notNull(),
  toEmail: text("to_email").notNull(),
  subject: text("subject").notNull(),
  body: text("body").notNull(),
  createdAt: integer("created_at").notNull(),
});
